#!/usr/bin/env python
"""Quadratic Primes"""
from P7 import is_prime

MAX = 1000


def main():
    """
    Find the product a * b of coefficients that produce the most quadratic
    primes.
    """
    max_primes = 0
    for a in range(-MAX, MAX + 1):
        # this could be improved by generating only prime values of b
        for b in range(-MAX, MAX + 1):
            num_primes = number_of_primes(a, b)
            if num_primes > max_primes:
                max_primes = num_primes
                max_a = a
                max_b = b
    return max_a, max_b, max_a * max_b


def number_of_primes(a, b):
    """Return the number of quadratic primes generated by coefficients a, b."""
    n = 0
    while(is_prime(quadratic(a, b, n))):
        n += 1
    return n


def quadratic(a, b, n):
    """Returns n^2 + an + b."""
    return n * n + a * n + b


if __name__ == '__main__':
    print main()
